<?xml version="1.0"?>
<package format="3">
  <name>ehand6_ctrl</name>
  <version>0.1.0</version>
  <description>ROS 2 node for the HitBot eHand-6 over SocketCAN FD (unofficial)</description>
  <maintainer email="tsusaka@ucl.nuee.nagoya-u.ac.jp">tsusaka</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>ehand6_msgs</depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-tk</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
